services:
  backend:
    # build: ./backend
    image: vinguyenthaotrinh/meow-care:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
  
  frontend:
    # build: ./frontend
    image: vinguyenthaotrinh/meow-care-fe:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
