version: "3.8"
services:
  backend:
    # build: ./backend
    image: vinguyenthaotrinh/meow-care:latest
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
